export const NARRATION: Record<string, string> = {
  hero: 'Meet Aura — the intelligent agent for your meetings. It records the conversation, understands what matters, guides people privately in the moment, and turns approved knowledge into memory. From there, Aura can generate any artifact your team designs: a business case, checklist, brief, report, workflow, or something custom.',
  'operating-loop': 'Think of Aura as a loop, not a static tool. It records and understands the meeting. It gives private guidance when something important comes up. It saves approved decisions to memory. Then it calls the right pipeline to create the artifact your team needs — any repeatable output, not just a fixed document type.',
  'meeting-agent': 'Aura records the meeting, but recording is only the first layer. While the conversation is happening, Aura understands context, risks, numbers, owners, and open questions. It can quietly guide the right person at the right time, without interrupting the room.',
  'living-memory': 'When people leave, knowledge walks out the door. Aura makes sure it doesn\'t. Every meeting, document, and decision becomes searchable memory that compounds over time.',
  'many-more': 'SOPs, onboarding packs, project briefs, proposals, audit reports — anything your team writes repeatedly. Set the template once. Aura produces it on demand.',
  architecture: 'Under the hood: specialist AI nodes, the right tools at the right moment, and one shared memory every workflow draws from. Memory-grounded. Always learning.',
  dashboards: 'Executive overview. Live pipelines. Approvals waiting on you. Automated insight reports. Everything your organisation needs to see — in role-appropriate dashboards.',
  knowledge: 'Two libraries, one platform: every document Aura creates — fully versioned — and every process your organisation documents. Search by meaning, revert in one click.',
  citations: 'Ask in plain English. Get an answer drawn from your own knowledge — with the exact source cited. Verifiable proof, not guesswork.',
  learning: 'Every edit you make becomes a proposed rule. Approve it once — Aura follows your standard automatically, forever.',
  security: 'Your knowledge is your edge. Aura keeps it segmented, encrypted end-to-end, and never used to train anyone else\'s AI.',
  'org-brain': 'The department brains shown here are illustrative — every organisation can have different teams, functions, and structures. The idea is simple: each team keeps private memory, approved knowledge can flow into the organisation brain, and cross-team sharing always requires explicit human approval.',
  'artifact-pipeline': 'Artifact pipelines are flexible. In chat, you describe the trigger, inputs, steps, reviewers, and output. After a meeting, Aura uses the recording, transcript, shared files, and memory, then calls the right pipeline to generate any artifact your organisation has designed.',
  'human-loop': 'Aura drafts. You decide. Nothing becomes final or enters memory without a named human signing off.',
  'access-control': 'Org Admin. Department Admin. Member. Viewer. Clear roles, enforced everywhere — with explicit approval for any cross-team sharing.',
  closing: 'Aura by PRM. In your meetings. In your memory. In your documents. Secure, human-approved, and under your control.',
};
