export const NARRATION: Record<string, string> = {
  hero: 'Meet Aura — the AI agent built for how your organisation actually works. It joins your meetings, builds living memory, and turns every decision into a document. Not a chatbot. Your organisation\'s shared brain.',
  'operating-loop': 'Aura runs one continuous loop: listen in meetings, guide you privately, save to memory, generate artifacts, and learn from every approval — all secure, human-approved, and access-controlled.',
  'meeting-agent': 'Aura doesn\'t just record your meeting. It understands it — and whispers insights only you can see. A risk to flag. A number to verify. The right question at the right moment.',
  'living-memory': 'When people leave, knowledge walks out the door. Aura makes sure it doesn\'t. Every meeting, document, and decision becomes searchable memory that compounds over time.',
  artifacts: 'One conversation. One review. The business case, requirements doc, action items, and backlog — drafted with sources attached, ready for human sign-off.',
  'many-more': 'SOPs, onboarding packs, project briefs, proposals, audit reports — anything your team writes repeatedly. Set the template once. Aura produces it on demand.',
  architecture: 'Under the hood: specialist AI nodes, the right tools at the right moment, and one shared memory every workflow draws from. Memory-grounded. Always learning.',
  dashboards: 'Executive overview. Live pipelines. Approvals waiting on you. Automated insight reports. Everything your organisation needs to see — in role-appropriate dashboards.',
  knowledge: 'Two libraries, one platform: every document Aura creates — fully versioned — and every process your organisation documents. Search by meaning, revert in one click.',
  citations: 'Ask in plain English. Get an answer drawn from your own knowledge — with the exact source cited. Verifiable proof, not guesswork.',
  learning: 'Every edit you make becomes a proposed rule. Approve it once — Aura follows your standard automatically, forever.',
  security: 'Your knowledge is your edge. Aura keeps it segmented, encrypted end-to-end, and never used to train anyone else\'s AI.',
  'human-loop': 'Aura drafts. You decide. Nothing becomes final or enters memory without a named human signing off.',
  'access-control': 'Org Admin. Department Admin. Member. Viewer. Clear roles, enforced everywhere — with explicit approval for any cross-team sharing.',
  closing: 'Aura by PRM. In your meetings. In your memory. In your documents. Secure, human-approved, and under your control.',
};
